# Generated by Django 4.2.4 on 2023-08-17 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("whiteboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="whiteboard",
            old_name="created_by",
            new_name="user",
        ),
    ]
