# Generated by Django 4.2.4 on 2023-08-19 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("whiteboard", "0002_rename_created_by_whiteboard_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("line", "line"),
                            ("shape", "shape"),
                            ("text", "text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField()),
                ("index_number", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name="whiteboard",
            index=models.Index(
                fields=["user", "name"], name="whiteboard__user_id_911b4d_idx"
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="white_board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="whiteboard.whiteboard"
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="drawing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="whiteboard.drawing"
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="drawing",
            index=models.Index(
                fields=["white_board", "name"], name="whiteboard__white_b_8ad35f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["drawing", "user"], name="whiteboard__drawing_1346a8_idx"
            ),
        ),
    ]
